language: ruby
rvm:
  - 2.7

git:
  depth: 1
  submodules: true
branches:
  only:
    - master

before_install:
  - nvm install 12.0

install:
  - bundle config set path vendor/bundle
  - bundle install
  - npm ci

cache:
  - directories:
      - vendor/bundle
      - node_modules

script:
  - npm run build
  - JEKYLL_ENV=production bundle exec jekyll build
  - tools/html-proofer.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: build
  repo: btjanaka/btjanaka.github.io
  target_branch: master
