name: Bryon Tjanaka
email: bryon@btjanaka.net
description: >
  Personal website of Bryon Tjanaka.
footer_text: >
  Powered by <a href="http://jekyllrb.com/">Jekyll</a> with <a
  href="https://github.com/alshedivat/al-folio">al-folio</a> theme. Hosted by <a
  href="https://pages.github.com/">GitHub Pages</a>.

url: # base hostname & protocol - do not use
baseurl: # site subpath, e.g. /blog/
last_updated: "Dec. 2019" # can leave blank
timezone: America/Los_Angeles

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# To achieve this, change serve_og_meta to true and then provide the URL of the
# preview image as the value of og_image.
serve_og_meta: true # Include Open Graph meta tags in the HTML head
og_image: /assets/img/open-graph-img.png # Site-wide (default for all links) Open Graph preview img
# -----------------------------------------------------------------------------
# Social integration - Leave blank to exclude
# -----------------------------------------------------------------------------
github_username: btjanaka
twitter_username:
linkedin_username: btjanaka
scholar_userid:
orcid_id:
medium_username:
quora_username:
publons_id:
research_gate_profile:
blogger_url:

contact_note: >
  Best reached via email

google_analytics: # google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Blog
blog_description:

# Pagination
paginate: 5
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: "Newer"
    older: "Older"

# Comments
disqus_shortname: btjanaka

# Optional features
show_social_icons: false
enable_anchorjs: false
enable_katex: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 3

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Source and destination directories
source: src
destination: build

# Build settings
markdown: kramdown
highlighter: pygments

# Includes and excludes
include: ["_pages"]
exclude: ["vendor"]

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-paginate
  - jekyll/scholar
  - jemoji

# Jekyll-Scholar
scholar:
  last_name: Einstein

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Serve settings
# -----------------------------------------------------------------------------

port: 8686
livereload: true

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
